// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Users__SignupController from "./users/signup_controller"
application.register("users--signup", Users__SignupController)
