name: Tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports: ["5432:5432"]
      redis:
        image: redis
        ports: ["6379:6379"]
        options: --entrypoint redis-server
      selenium_chrome:
        image: seleniarm/standalone-chromium
        ports:
          - 4444:4444

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler: default
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: yarn

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y -qq libvips
          yarn install

      - name: Standardrb Check
        run: bundle exec standardrb

      - name: ERB Lint
        run: bundle exec erblint --lint-all

      - name: Rspec
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/test
          REDIS_URL: redis://localhost:6379
          RAILS_ENV: test
        run: |
          bundle exec bin/rails assets:precompile
          bin/rails db:test:prepare
          bundle exec rspec
